version: 2.1

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout:
          path: ~/repo
      - run: 
          name: Installer les dépendances et exécuter les tests dans le backend
          command: |
            cd ~/repo
            if [ -d "3w5-h24-tp2-backend" ]; then
              echo "Le répertoire backend existe déjà, suppression..."
              rm -rf 3w5-h24-tp2-backend
            fi
            git clone -b backend https://github.com/gwefoss/labo2CircleCI.git 3w5-h24-tp2-backend
            cd 3w5-h24-tp2-backend
            npm install
            npm test

  integrationFrontend:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout:
          path: ~/frontend
      - run:
          name: Cloner et préparer le répertoire frontend
          command: |
            if [ -d "3w5-h24-tp2-frontend" ]; then
              echo "Le répertoire frontend existe déjà, suppression..."
              rm -rf 3w5-h24-tp2-frontend
            fi
            git clone -b frontend https://github.com/gwefoss/labo2CircleCI.git 3w5-h24-tp2-frontend
            cd 3w5-h24-tp2-frontend
            npm install
            npm run build
      - checkout:
          path: ~/backend
      - run:
          name: Préparer le répertoire backend et copier le build frontend
          command: |
            if [ -d "~/backend/3w5-h24-tp2-backend" ]; then
              echo "Le répertoire backend pour intégration existe déjà, suppression..."
              rm -rf ~/backend/3w5-h24-tp2-backend
            fi
            git clone -b backend https://github.com/gwefoss/labo2CircleCI.git ~/backend/3w5-h24-tp2-backend
            mkdir -p ~/backend/3w5-h24-tp2-backend/public
            cp -R ~/frontend/3w5-h24-tp2-frontend/build/* ~/backend/3w5-h24-tp2-backend/public/
      - persist_to_workspace:
          root: ~/backend
          paths:
            - 3w5-h24-tp2-backend

  deploiement:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - attach_workspace:
          at: ~/backend
      - run:
          name: Lister le contenu du répertoire backend
          command: |
            cd ~/backend/3w5-h24-tp2-backend
            ls -Rl

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkoutEtTests:
          filters:
            branches:
              only: backend
      - integrationFrontend:
          requires:
            - checkoutEtTests
          filters:
            branches:
              only: frontend
      - deploiement:
          requires:
            - integrationFrontend
          filters:
            branches:
              only: backend
